### ISSUE TITLE
Wrong commit for release v11.5.0?

### ISSUE THREAD

**Issue by scribam** [RetroAchievements/rcheevos#361] opened 2024-07-28 07:31 UTC
@Jamiras [v11.5.0](https://github.com/RetroAchievements/rcheevos/releases/tag/v11.5.0) and [v11.4.0](https://github.com/RetroAchievements/rcheevos/releases/tag/v11.4.0) use the same commit d54cf8f1059cebc90a6f5ecdf03df69259f22054

I guess the expected commit for [v11.5.0](https://github.com/RetroAchievements/rcheevos/releases/tag/v11.5.0) is https://github.com/RetroAchievements/rcheevos/commit/563230b1c249774b4852c944dc7cdcb952c9e8e8

**Comment by Jamiras** [comment] 2024-07-28 13:05
Yep. Thanks. I was tagging master (instead of develop), which was intended, but hadn't merged develop into master yet.

**Closed by Jamiras** 2024-07-28 13:05 UTC
